site_name: Maksym Tanchuk's CV
site_author:
  TAN4UK
# repo_url: https://github.com/TAN4UKmax/CV-MKDocs
# repo_name: TAN4UKmax/CV-MKDocs

# Navigation through CV
nav:
  - Home: index.md
  # - Dev Test: dev/README_dev.md
  - Skills: skills.md
  - Experience: experience.md
  - Education: education.md
  - Languages: languages.md

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexers
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

# Changing apearance
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Extentions for highlighting code and icons support
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Footer setup
# Links to social pages in footer
extra:
  social:
    - icon: material/phone
      link: tel:+4915158846487
    - icon: material/email
      link: mailto:tan4ukmak7@gmail.com
      name: Email
    - icon: fontawesome/brands/telegram
      link: https://t.me/TAN4UK
      name: Telegram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tan4uk
      name: LinkedIn
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TAN4UKmax/
      name: GitHub

# Copyright at the bottom
copyright: |
  &copy; 2024 TAN4UK